#!/usr/bin/env bash
set -euo pipefail

FLAKE_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$FLAKE_DIR"

usage() {
    echo "Usage: $0 <hostname> [--hw-only|--sops-only]"
    echo ""
    echo "  hostname       desktop, laptop, or any host under modules/hosts/"
    echo "  --hw-only      only generate + wrap hardware config"
    echo "  --sops-only    only set up sops keys"
    echo "  (no flag)      full enrollment: hw + sops + flake lock"
    exit 1
}

HOST=""
MODE="full"

for arg in "$@"; do
    case "$arg" in
        --hw-only) MODE=hw ;;
        --sops-only) MODE=sops ;;
        --help|-h) usage ;;
        *) HOST="$arg" ;;
    esac
done

if [ -z "$HOST" ] && [ "$MODE" != "sops" ]; then
    usage
fi

# ── ensure nix tools are available ──────────────────────────────
ensure_tools() {
    local missing=()
    for cmd in "$@"; do
        command -v "$cmd" &>/dev/null || missing+=("$cmd")
    done
    if [ ${#missing[@]} -gt 0 ]; then
        echo "→ Installing required tools: ${missing[*]}"
        nix-shell -p sops age ssh-to-age --run "true" || {
            echo "! Could not install tools. Run:  nix-shell -p sops age ssh-to-age"
            return 1
        }
    fi
}

# ── hardware config ─────────────────────────────────────────────
gen_hardware() {
    local host="$1"
    local out="modules/hosts/$host/hardware-configuration.nix"

    if [ -f "$out" ] && ! grep -q "STUB\|TODO" "$out" 2>/dev/null; then
        echo "! $out already has real content — skipping (use --hw-only to force)"
        return 0
    fi

    echo "→ Generating hardware configuration for '$host'..."

    local tmp
    tmp=$(mktemp)
    sudo nixos-generate-config --show-hardware-config > "$tmp"

    {
        echo "# Generated by nixos-generate-config — wrapped by scripts/enroll.sh"
        echo "# Regenerate with: just hw $host"
        echo "{ self, ... }:"
        echo "{"
        echo "  flake.nixosModules.${host}Hardware ="
        echo "    { config, lib, pkgs, modulesPath, ... }:"
        echo "    {"

        # Indent the generated output by 6 spaces
        sed 's/^/      /' "$tmp"

        echo "    };"
        echo "}"
    } > "$out"

    rm "$tmp"
    echo "   ✓ Saved to $out"
}

# ── sops setup ───────────────────────────────────────────────────
setup_sops() {
    echo "→ Setting up sops..."

    ensure_tools sops age ssh-to-age

    # SSH key
    if [ ! -f ~/.ssh/id_ed25519 ]; then
        echo "   No SSH key found. Generating one..."
        ssh-keygen -t ed25519 -C "flyewic@gmail.com" -f ~/.ssh/id_ed25519 -N ""
        echo "   ✓ SSH key generated at ~/.ssh/id_ed25519"
    fi

    # Age identity
    mkdir -p ~/.config/sops/age
    if ssh-to-age -private-key -i ~/.ssh/id_ed25519 > ~/.config/sops/age/keys.txt 2>/dev/null; then
        : # ok
    else
        ssh-to-age -private-key < ~/.ssh/id_ed25519 > ~/.config/sops/age/keys.txt
    fi
    chmod 600 ~/.config/sops/age/keys.txt
    echo "   ✓ Age identity at ~/.config/sops/age/keys.txt"

    # .sops.yaml
    ADMIN_KEY=$(ssh-to-age < ~/.ssh/id_ed25519.pub)
    if grep -q "age1_REPLACE_ME" .sops.yaml 2>/dev/null; then
        sed -i "s|age1_REPLACE_ME|$ADMIN_KEY|" .sops.yaml
        echo "   ✓ Admin key written to .sops.yaml: $ADMIN_KEY"
    else
        echo "   - .sops.yaml already has a real key — skipping"
    fi

    # Encrypted secrets file
    if [ -f secrets/secrets.yaml ]; then
        if head -1 secrets/secrets.yaml 2>/dev/null | grep -qi "PLACEHOLDER"; then
            rm secrets/secrets.yaml
        fi
    fi

    if [ ! -f secrets/secrets.yaml ]; then
        cat > /tmp/secrets-init.yaml << 'YAML'
# Secrets for the nixconf flake.
# Add your secrets here. Example:
#   user-password: <hash from mkpasswd -m sha-512>
YAML
        sops --encrypt /tmp/secrets-init.yaml > secrets/secrets.yaml
        rm /tmp/secrets-init.yaml
        echo "   ✓ Encrypted secrets/secrets.yaml created"
        echo ""
        echo "   Add secrets now:"
        echo "     sops secrets/secrets.yaml"
        echo "   Generate a password hash:"
        echo "     mkpasswd -m sha-512"
    else
        echo "   - secrets/secrets.yaml already exists — skipping"
    fi
}

# ── flake lock ───────────────────────────────────────────────────
lock_flake() {
    echo "→ Locking flake..."
    nix --extra-experimental-features 'nix-command flakes' flake lock
    echo "   ✓ Flake locked"
}

# ── main ─────────────────────────────────────────────────────────
case "$MODE" in
    hw)
        gen_hardware "$HOST"
        ;;
    sops)
        setup_sops
        ;;
    full)
        gen_hardware "$HOST"
        echo ""
        setup_sops
        echo ""
        lock_flake
        echo ""
        echo "══ Enrollment complete for '$HOST' ══"
        echo ""
        echo "  Next steps:"
        echo "    1. Add secrets:        sops secrets/secrets.yaml"
        echo "    2. Generate password:  mkpasswd -m sha-512"
        echo "    3. First switch:       sudo nixos-rebuild switch --flake .#$HOST"
        echo ""
        echo "  After first switch, use: just switch"
        ;;
esac
